// apps/me-via-you/src/lib/components/ThemeToggle.svelte
<script lang="ts">
  import { getThemeMode, toggleThemeMode, type ThemeMode } from "$lib/theme-mode";
  import { Moon, Sun } from "@lucide/svelte";
  import { onMount } from "svelte";

  let mode = $state<ThemeMode>("dark");

  onMount(() => {
    mode = getThemeMode();
  });

  function toggle() {
    mode = toggleThemeMode();
  }
</script>

<button
  type="button"
  class="inline-flex items-center justify-center rounded border border-accent/40 p-2 text-accent transition-colors hover:bg-accent/10"
  aria-label={mode === "dark" ? "Switch to light mode" : "Switch to dark mode"}
  title={mode === "dark" ? "Light mode" : "Dark mode"}
  onclick={toggle}
>
  {#if mode === "dark"}
    <Sun size={16} aria-hidden="true" />
  {:else}
    <Moon size={16} aria-hidden="true" />
  {/if}
</button>

// apps/heimdall/src/components/ThemeToggle.tsx
import { Moon, Sun } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useTheme } from "@/hooks/useTheme";

export function ThemeToggle() {
  const { theme, toggle } = useTheme();
  const isDark = theme === "dark";

  return (
    <Button
      type="button"
      variant="outline"
      size="sm"
      className="shrink-0 gap-2 text-muted-foreground"
      aria-label={isDark ? "Switch to light theme" : "Switch to dark theme"}
      onClick={toggle}
    >
      {isDark ? <Sun className="h-3.5 w-3.5" /> : <Moon className="h-3.5 w-3.5" />}
      <span className="hidden sm:inline">Theme</span>
    </Button>
  );
}
