// apps/me-via-you/src/routes/(auth)/sign-up/+page.svelte
<script lang="ts">
  import { goto } from "$app/navigation";
  import { page } from "$app/state";
  import { authClient } from "$lib/auth-client";
  import { Button } from "$lib/components/ui/button";
  import { Input } from "$lib/components/ui/input";
  import { Label } from "$lib/components/ui/label";

  const id = $props.id();

  const redirectTo = $derived(page.url.searchParams.get("redirect") ?? "/");
  const loginHref = $derived(redirectTo === "/" ? "/login" : `/login?redirect=${encodeURIComponent(redirectTo)}`);

  let name = $state("");
  let email = $state("");
  let username = $state("");
  let password = $state("");
  let confirmPassword = $state("");
  let error = $state<string | null>(null);
  let loading = $state(false);

  const strongPasswordRegex = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$/;

  async function handleSubmit(e: SubmitEvent) {
    e.preventDefault();
    error = null;

    if (password !== confirmPassword) {
      error = "Passwords do not match";
      return;
    }

    if (!strongPasswordRegex.test(password)) {
      error = "Password must be at least 8 characters and contain uppercase, lowercase, number, and special character";
      return;
    }

    loading = true;

    try {
      const result = await authClient.signUp.email({
        email,
        password,
        name,
        username,
        callbackURL: `${window.location.origin}/verify-email`,
      });

      if (result.error) {
        error = result.error.message ?? "Failed to create account. Please try again.";
        loading = false;
        return;
      }

      await goto(`/check-email?type=signup&email=${encodeURIComponent(email)}`);
    } catch (err) {
      console.error(err);
      error = "Something went wrong!";
      loading = false;
    }
  }
</script>

<form class="auth-form" onsubmit={handleSubmit}>
  {#if error}
    <div class="auth-error">{error}</div>
  {/if}

  <div class="flex flex-col gap-5">
    <div class="flex flex-col items-center gap-2 text-center">
      <h1 class="text-2xl font-bold">Create your account</h1>
      <p class="text-balance text-sm text-muted-foreground">Sign up for Me Via You</p>
    </div>

    <div class="grid gap-2">
      <Label for="email-{id}">Email</Label>
      <Input id="email-{id}" type="email" placeholder="you@example.com" required bind:value={email} disabled={loading} />
      <p class="text-xs text-muted-foreground">We use this for account recovery and verification.</p>
    </div>

    <div class="grid grid-cols-1 gap-4 sm:grid-cols-2">
      <div class="grid gap-2">
        <Label for="name-{id}">Name</Label>
        <Input id="name-{id}" type="text" required bind:value={name} disabled={loading} />
      </div>
      <div class="grid gap-2">
        <Label for="username-{id}">Username</Label>
        <Input id="username-{id}" type="text" required bind:value={username} disabled={loading} />
      </div>
    </div>

    <div class="grid grid-cols-1 gap-4 sm:grid-cols-2">
      <div class="grid gap-2">
        <Label for="password-{id}">Password</Label>
        <Input id="password-{id}" type="password" required bind:value={password} disabled={loading} />
      </div>
      <div class="grid gap-2">
        <Label for="confirm-password-{id}">Confirm password</Label>
        <Input id="confirm-password-{id}" type="password" required bind:value={confirmPassword} disabled={loading} />
      </div>
    </div>
    <p class="text-xs text-muted-foreground">Use at least 8 characters with upper, lower, number, and special character.</p>

    <Button type="submit" disabled={loading} class="w-full">
      {#if loading}
        Please wait…
      {:else}
        Create account
      {/if}
    </Button>

    <p class="text-center text-sm text-muted-foreground">
      Already registered?
      <a href={loginHref} class="text-primary underline-offset-2 hover:underline">Sign in</a>
    </p>
  </div>
</form>

// apps/web/watchlist/src/components/auth/sign-up.tsx
import { useNavigate } from "@tanstack/react-router";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Field, FieldContent, FieldError, FieldLabel } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { authClient } from "@/lib/auth-client";

interface SignUpFormProps {
  redirect: string;
}

export function SignUpForm({ redirect }: SignUpFormProps) {
  const navigate = useNavigate();
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [name, setName] = useState("");
  const [username, setUsername] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError(null);
    setIsLoading(true);

    try {
      await authClient.signUp.email({
        email,
        password,
        name,
      });

      navigate({ to: redirect });
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to sign up");
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="flex min-h-screen items-center justify-center p-4">
      <Card className="w-full max-w-md">
        <CardHeader>
          <CardTitle>Sign Up</CardTitle>
          <CardDescription>Create a new account to get started</CardDescription>
        </CardHeader>
        <CardContent>
          <form onSubmit={handleSubmit} className="space-y-4">
            <Field>
              <FieldLabel htmlFor="name">Name</FieldLabel>
              <FieldContent>
                <Input
                  id="name"
                  type="text"
                  value={name}
                  onChange={(e) => setName(e.target.value)}
                  required
                  autoComplete="name"
                  placeholder="John Doe"
                />
              </FieldContent>
            </Field>

            <Field>
              <FieldLabel htmlFor="username">Username (optional)</FieldLabel>
              <FieldContent>
                <Input
                  id="username"
                  type="text"
                  value={username}
                  onChange={(e) => setUsername(e.target.value)}
                  autoComplete="username"
                  placeholder="johndoe"
                />
              </FieldContent>
            </Field>

            <Field>
              <FieldLabel htmlFor="email">Email</FieldLabel>
              <FieldContent>
                <Input
                  id="email"
                  type="email"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  required
                  autoComplete="email"
                  placeholder="you@example.com"
                />
              </FieldContent>
            </Field>

            <Field>
              <FieldLabel htmlFor="password">Password</FieldLabel>
              <FieldContent>
                <Input
                  id="password"
                  type="password"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  required
                  autoComplete="new-password"
                  placeholder="Create a password"
                />
              </FieldContent>
            </Field>

            {error && <FieldError>{error}</FieldError>}

            <Button type="submit" className="w-full" disabled={isLoading}>
              {isLoading ? "Creating account..." : "Sign Up"}
            </Button>

            <div className="text-center text-sm text-muted-foreground">
              Already have an account?{" "}
              <button
                type="button"
                onClick={() => navigate({ to: "/auth/sign-in", search: { redirect } })}
                className="text-primary hover:underline"
              >
                Sign in
              </button>
            </div>
          </form>
        </CardContent>
      </Card>
    </div>
  );
}
